# Generated by Django 4.2.1 on 2023-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(default=0)),
                ('sr', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Confirm', 'Confirm'), ('Tentative ', 'Tentative ')], default='Tentative ', max_length=10)),
                ('event_timing', models.CharField(choices=[('Day', 'Day'), ('Night ', 'Night ')], default='Night ', max_length=10)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField(blank=True)),
                ('no_of_people', models.IntegerField(default=0)),
                ('setup', models.CharField(choices=[('Normal', 'Normal'), ('Delux', 'Delux '), ('VIP', 'VIP ')], default='Delux', max_length=10)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_number', models.BigIntegerField(blank=True)),
                ('per_head', models.IntegerField(default=0)),
                ('extra_charges', models.IntegerField(blank=True)),
                ('food_menu', models.CharField(blank=True, max_length=200)),
                ('detials', models.TextField(blank=True)),
                ('total_amount', models.IntegerField(blank=True)),
                ('recieved_amount', models.IntegerField(blank=True)),
                ('remaining_amount', models.IntegerField(blank=True)),
            ],
        ),
    ]
