# Generated by Django 4.2.1 on 2023-10-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpense',
            name='total_expense',
            field=models.BigIntegerField(blank=True, editable=False),
        ),
    ]
