# Generated by Django 4.2.1 on 2023-05-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='remaining_amount',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='total_amount',
            field=models.IntegerField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name='EventExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pakwan_bill', models.IntegerField(blank=True, default=0)),
                ('electicity', models.IntegerField(blank=True, default=0)),
                ('naan_qty', models.IntegerField(blank=True, default=0)),
                ('naan_bill', models.IntegerField(blank=True, default=0)),
                ('cold_drink', models.IntegerField(blank=True, default=0)),
                ('cold_drink_bill', models.IntegerField(blank=True, default=0)),
                ('water', models.IntegerField(blank=True, default=0)),
                ('water_bill', models.IntegerField(blank=True, default=0)),
                ('bbq_kg', models.CharField(blank=True, max_length=200)),
                ('diesel_ltr', models.IntegerField(blank=True, default=0)),
                ('no_of_waiters', models.IntegerField(blank=True, default=0)),
                ('waiters_bill', models.IntegerField(blank=True, default=0)),
                ('stuff_bill', models.IntegerField(blank=True, default=0)),
                ('dhobi', models.IntegerField(blank=True, default=0)),
                ('other_expense', models.IntegerField(blank=True, default=0)),
                ('other_expense_detals', models.TextField(blank=True)),
                ('setup_bill', models.IntegerField(blank=True, default=0)),
                ('decor', models.CharField(blank=True, max_length=200)),
                ('decor_bill', models.IntegerField(blank=True, default=0)),
                ('total_expense', models.IntegerField(blank=True, editable=False)),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.eventsale')),
            ],
        ),
    ]
