# Generated by Django 4.2.1 on 2023-05-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_eventsale_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexpense',
            name='bbq_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
