# Generated by Django 4.2.1 on 2023-05-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_eventexpense_bbq_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventexpense',
            old_name='bill_no',
            new_name='bill',
        ),
    ]
