# Generated by Django 4.2.1 on 2023-10-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_eventexpense_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpense',
            name='expense_date',
            field=models.DateField(),
        ),
    ]
