# Generated by Django 4.2.1 on 2023-10-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_eventexpense_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexpense',
            name='x',
        ),
    ]
