# Generated by Django 4.2.1 on 2023-05-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_bill_no_eventexpense_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpense',
            name='bbq_price',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
