# Generated by Django 4.2.1 on 2023-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_eventexpense_bbq_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventexpense',
            name='bbq_kg',
        ),
        migrations.AddField(
            model_name='eventexpense',
            name='bbq_kg_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
