# Generated by Django 4.2.1 on 2023-10-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_eventexpense_total_expense'),
        ('ecommerce', '0005_remove_eventexpense_x'),
    ]

    operations = [
    ]
