# Generated by Django 4.2.1 on 2023-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_eventexpense_bbq_kg_eventexpense_bbq_kg_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpense',
            name='waiters_bill',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='eventexpense',
            name='water_bill',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
