# Generated by Django 4.2.1 on 2023-05-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_eventexpense_waiters_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpense',
            name='naan_bill',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
