# Generated by Django 4.2.1 on 2023-10-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_eventexpense_cold_drink_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexpense',
            name='bbq_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='eventexpense',
            name='water_bottles_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
