# Generated by Django 4.2.1 on 2023-06-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_eventexpense_cold_drink_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='remaining_amount',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='total_amount',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
