# Generated by Django 4.2.1 on 2023-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_eventexpense_bbq_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventexpense',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
