# Generated by Django 4.2.1 on 2023-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_eventsale_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='recieved_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
