# Generated by Django 4.2.1 on 2023-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_eventexpense_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventexpense',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
