# Generated by Django 4.2.1 on 2023-06-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_eventsale_recieved_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='bill_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='no_of_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='per_head',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='sr',
            field=models.IntegerField(),
        ),
    ]
