# Generated by Django 4.2.1 on 2023-10-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_eventexpense_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsale',
            name='hall_charges',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
