# Generated by Django 4.2.1 on 2023-10-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_eventsale_hall_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='mykitchenexpense',
            name='customer_name',
            field=models.CharField(default='Nill', max_length=50),
            preserve_default=False,
        ),
    ]
