# Generated by Django 4.2.1 on 2023-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_eventsale_bill_no_alter_eventsale_no_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='bill_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='no_of_people',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='per_head',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='sr',
            field=models.IntegerField(null=True),
        ),
    ]
