# Generated by Django 4.2.1 on 2023-06-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_alter_eventsale_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='event_timing',
            field=models.CharField(choices=[('Day', 'Day'), ('Night ', 'Night')], default='Night ', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='setup',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Delux', 'Delux'), ('VIP', 'VIP')], default='Delux', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventsale',
            name='status',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Tentative ', 'Tentative')], default='Tentative ', max_length=10),
        ),
    ]
