# Generated by Django 4.2.1 on 2023-06-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_deals_price_per_head'),
        ('ecommerce', '0022_eventsale_deals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='deals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.deals'),
        ),
    ]
