# Generated by Django 4.2.1 on 2023-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_alter_eventsale_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='bill_no',
            field=models.IntegerField(auto_created=True, editable=False, null=True, unique=True),
        ),
    ]
