# Generated by Django 4.2.1 on 2023-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsale',
            name='entry_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventsale',
            name='stage_charges',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
