# Generated by Django 4.2.1 on 2023-08-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_eventsale_entry_charges_eventsale_stage_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsale',
            name='payment_details',
            field=models.TextField(blank=True),
        ),
    ]
