# Generated by Django 4.2.1 on 2023-08-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_eventsale_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsale',
            name='payment_details',
            field=models.TextField(),
        ),
    ]
