# Generated by Django 4.2.1 on 2023-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_alter_eventsale_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsale',
            name='payment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
