# Generated by Django 4.2.1 on 2023-08-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_alter_eventsale_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsale',
            name='total_menu',
            field=models.IntegerField(default=0),
        ),
    ]
