# Generated by Django 4.2.1 on 2023-08-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_eventsale_total_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsale',
            name='location',
            field=models.CharField(blank=True, default='Hall', max_length=10),
        ),
    ]
