# Generated by Django 4.2.1 on 2023-08-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_eventsale_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsale',
            name='gents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventsale',
            name='ladies',
            field=models.IntegerField(default=0),
        ),
    ]
