# Generated by Django 4.2.1 on 2023-09-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_eventsale_gents_eventsale_ladies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchensale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_details', models.TextField(max_length=300)),
                ('mutton', models.CharField(max_length=50)),
                ('chicken', models.CharField(max_length=50)),
                ('beef', models.CharField(max_length=50)),
                ('rice', models.CharField(max_length=50)),
                ('dahi', models.CharField(max_length=50)),
                ('doodh', models.CharField(max_length=50)),
                ('sabzi', models.CharField(max_length=50)),
                ('fruits', models.CharField(max_length=50)),
                ('khoya_cream_paneer', models.CharField(max_length=50)),
                ('dry_fruits', models.CharField(max_length=50)),
                ('oil', models.CharField(max_length=50)),
                ('other_items_bill', models.CharField(max_length=50)),
                ('other_items_desc', models.CharField(max_length=50)),
                ('total_bill', models.CharField(max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.eventsale')),
            ],
        ),
    ]
