# Generated by Django 4.2.1 on 2023-09-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_kitchensale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kitchensale',
            new_name='Kitchenexpense',
        ),
    ]
