# Generated by Django 4.2.1 on 2023-09-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_rename_kitchensale_kitchenexpense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kitchenexpense',
            new_name='MyKitchenexpense',
        ),
    ]
