# Generated by Django 4.2.1 on 2023-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_rename_kitchenexpense_mykitchenexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customer_name',
            field=models.CharField(default='nill', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(default='nill', max_length=10),
            preserve_default=False,
        ),
    ]
