# Generated by Django 4.2.1 on 2023-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalExpense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionandrepair',
            name='expense_by',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyexpenses',
            name='expense_by',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='expense_by',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='expense_by',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
