# Generated by Django 4.2.1 on 2023-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalExpense', '0002_constructionandrepair_expense_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=120)),
                ('contact_number', models.BigIntegerField(default=0)),
                ('vendor_for', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
