# Generated by Django 4.2.1 on 2023-10-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='date_added',
        ),
    ]
