# Generated by Django 4.2.1 on 2023-05-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='MyProducts',
        ),
    ]
