# Generated by Django 4.2.1 on 2023-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='price_per_head',
            field=models.IntegerField(default=0),
        ),
    ]
