# Generated by Django 4.2.1 on 2023-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_deals_price_per_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='price_per_head',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
