# Generated by Django 4.2.1 on 2023-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproducts',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myproducts',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
    ]
