# Generated by Django 4.2.1 on 2023-07-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_eventsale_bill_no'),
        ('items', '0010_myproducts_initial_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='function',
            field=models.ForeignKey(default=1121, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.eventsale'),
            preserve_default=False,
        ),
    ]
