# Generated by Django 4.2.1 on 2023-07-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_usage_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproducts',
            name='initial_quantity',
        ),
        migrations.RemoveField(
            model_name='myproducts',
            name='remaining_quantity',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
