# Generated by Django 4.2.1 on 2023-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_myproducts_initial_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproducts',
            name='manufacturer_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
