# Generated by Django 4.2.1 on 2023-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_myproducts_manufacturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproducts',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product_images/%Y/%m'),
        ),
    ]
